apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:ZVwyhSPNmef0TP5zVTdbkB/X3mdWH4uJQ/NFHXBqp9Vy5OnY2ourFe4+jqmtKE7xB71J7tU=,iv:PQdRxSWHBK6N6GJ0WsG5IfP0KtPztm6ta7/1Drylrzw=,tag:B5vJs7Hx+TZnHWKo7YtDCQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmanpscHVFbVU2cVJtNmpn
            Q0ZkU2JQUzhpSW9WV3gwek5NTXBYOC9nM0RRCms2bzJoSnorbnFaejd5NmZ6MTlV
            QWFZNmNsaGgvWG56Q0FoUHU5MStvY0UKLS0tIEZORzJKeEhNekdHb3JEQmpLL09F
            UFp6dm1aQnMreTcyY1MyRUNWL2R5MkkKvP+a/lCPOGdVSl/zyOGaF20KKCUookB/
            CahLcy9ziOE2pXP4of6uStV7HsdY7yBwpBLFjZs/R92TiDdrYNAGNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lm0sz9afv6fdmpqcfsrhcfvkfcw6rgga20mpplrryxwcppfd6glq959w5j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T18:22:05Z"
    mac: ENC[AES256_GCM,data:KASMvEstCxl96zHpKm10I3OIIGEHanIVmpySjSyJ/GvkxEbtigRC0g1yvBWzUeasfse1JYOCTB9w726dPU1C0Bci+6DeOcFY6UbJkOIX86uqO9CLnSK6cxtC40offE3M4xFxvGVx6mBkFAj0jm4CS8ptxicbg8uywX1M4b84JsA=,iv:3JRWkMDnurnIVYyGz9798VqQG4vIqeKoJYzKYBFaO2Y=,tag:84TB4q0QCvCjIOIl8Dl1Tg==,type:str]
    version: 3.13.3
