apiVersion: v1
kind: Secret
metadata:
    name: r2-backup-credentials
    namespace: databases
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:SQIWt8BPSVrZaGwE6tnBCcVCrcDpjH9pkN3Lkm6sBQg=,iv:Awz/OtpIBKnWBcvMh/8KCC71pfcBKeHBTsokkHkOEn0=,tag:kaJYs4wXoYowVyj2yKMT0w==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:DLtl+WpNf7p5ZobROxdYkbFlqr1rXh2chyaArX8jBeX8l/x2kfch9O2RUfwc8MK+aVIRmJ8IHDMKBzbx87Hy5A==,iv:ChPDng9FNoKSGsEfQ68u95q7iiHMI+kMhTirCMpJfZI=,tag:5sq5NBzYbInMLrodBwOVPg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlU1pYbzJERWF6bVdpOHhh
            Q2JFK3FJV3Y2QTloMUpkakNMU1R4QUxvNTB3CmsvR1JGWk05RSs2TFd0WkxHN3dU
            U0RjaW1kL09SVHRjOERkRjZnU2pZMGMKLS0tIG9kR282YzVyVUx2NTdwR3UrYmV4
            MmpNbkYzSHhwZTVtSTNjYVpkUVJXcWMK3pfPbt/jrQAiocxdCObF2JSpEc82mVL6
            VvdcZpCs6LM0nLDkDE4V1DnKUj5MibrZF1Mi6La+zl9HGRJReJlobQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lm0sz9afv6fdmpqcfsrhcfvkfcw6rgga20mpplrryxwcppfd6glq959w5j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T18:22:05Z"
    mac: ENC[AES256_GCM,data:thTv1XqZ5Bj3GkRCkqy2R917XZwfEg7mO71I6BloxWEWpd3dt/nzkmxwjkGdsMoodFr5GPhEqqY0ViFTWbWL1ro5bk1XfzL2zcmKOrc7efGjaqQtyYMnI3246AVykrXKR+zGteWaacSyywiCE1hxe1AMpHZQIMJnAyxTyqE1FXw=,iv:u80vF+jygLO/VLnQf6Y63x+1KkqsnyXT/MRhYno8TOU=,tag:F128O1POluK71TDxNxXm+w==,type:str]
    version: 3.13.3
