apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull
    namespace: website
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:rBAGA7fWZpBeV9tF04gZnQ8T0QnPHtxsTXZWvTEiQE8aWb1MmfUVq4wLJbU2z7Re1h018TqopxkgOyPIncX4dcPtzTGGRk/JfURxHBpdl/LVVqp1KS/19rcR/97M4MBNwXjVuHby9zV/IoJvgzmHQQQK2h2OcUbA9kOHtfQuJxCDsyrXzG+skRupY4F9OTTeWYNiyJE3DkUa9gjUkoudpAQ6VnPhJ9xgtyQRSfWj9H3ay4E0RXTlUh4=,iv:qTSKg5rQDXKxMb6M9sO11CzIrSpBFoWFu7mJfeMOPFM=,tag:+10MeD3bCNNUbCWUv7Ww1w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dlBFOUN0cDVOZGFRVFNP
            NUVVRkxxL0l3blFiMW81M20rc2k4K2JLNnk4CmhVNGRldUo0UUljVFIrSUN3WEhB
            aDY5aTVxT2JadTlHSzdDMEtCWmY4K28KLS0tIEtZZVBwSlhvL3lQb25jdW5EeUUy
            UzlMUHd2MzRVNG5oaU5kOXdxcW1TUm8K1aZzV1eML22TeILS6SsnxB/9p2g/wzqr
            7IO6SQV9dzEfQJ7vU81STeBliVQJaYPca9AVKLdzihhQ/11YD2Vk2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lm0sz9afv6fdmpqcfsrhcfvkfcw6rgga20mpplrryxwcppfd6glq959w5j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T23:04:37Z"
    mac: ENC[AES256_GCM,data:o27LIZqM1GDnsd4RY/5q/vqAR7/Nsz+lCU+Cnp2Lxdz6aKukoEHzT+ZA07vwKgl7yX6nUVdRPJ00tN5uOd7FG9jQAR6kxu4gwckpwPlP49UsSUucGArmrgrNT+8BhA6CyPzQB5JW3zZarV65PEqWPzswhUwtS7JowSLlZMhfFMQ=,iv:geLJUQNMCdVNT0/OxWyI6gXhe2i5ZUQxliAVHv+of5I=,tag:Q7u0WeztNi3mDUZuhZPVig==,type:str]
    version: 3.13.3
