apiVersion: v1
kind: Secret
metadata:
    name: website
    namespace: website
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:21JluHKo7EdcHCcJo0han4SaNBr+SXBfwvVZiTd4SpTYoby7vGW4QCoXnULTlfW1AvFNvmrCf4OfchZuzFnBox+2RExik+HGB5JhlACDwuk6beBOmu3DgF6Oo2hunqPzZek9C1PF7PvES/o7fhd7xe3aLu8UvjDpIzb2nMQ6Ja7t3M4ApiGcX0i1,iv:VSMKSVWY5MkKUH8KIcpM0jAUlIo0+dBO1UgS5nLtJX4=,tag:FsmYC5HZiM+NpVh8kr/CKQ==,type:str]
    AUTH_SECRET: ENC[AES256_GCM,data:TOXlXZ6SDCKoHqknf8rs9Kky4D6AizkvKTxsWQslCYPplG2TRchAOBN7F7M=,iv:3feySv+IuU2Iiag+dzbZD15c6uJ6fSEbxzSW8DmiR1k=,tag:G6s4jQAIFsInH+xzY90eGQ==,type:str]
    CRON_SECRET: ENC[AES256_GCM,data:Is2ARSWXoRkl0PdObMUma9Do9ekxwPmb56kfBKMNxmPEVqnm0xQLVUn9F4IC3KmER6A4nZBEGcucSNhMaGMHIw==,iv:15lOV2kfJIcmjldI+asPlOwuv380RGMAiZJb7K98i+M=,tag:d18VP08a4bJ7ybfr0Tg0ZA==,type:str]
    AUTH_GITHUB_ID: ENC[AES256_GCM,data:8ypI707xBp8=,iv:O/SZ2KhVizGbbyXakt6LsF9hQxh/Yr0ibn5VV14dpuI=,tag:JGUkZGscGGJpX4lpbtEeUA==,type:str]
    AUTH_GITHUB_SECRET: ENC[AES256_GCM,data:4F+dbAa6mtQ=,iv:9vy8WMtqVKJcifAo0/zlqXo16ubaLhxWU0Kz+FUen90=,tag:0KQN6enc/LgM5n46beM/5w==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:bDaPXWtYnUM=,iv:EJPVIyI/qjYsIKive7V3bDcoHrqt0ZeFvD6CUaPQjOM=,tag:YwK74oMi45jWA3NjxVCobQ==,type:str]
    RESEND_API_KEY: ENC[AES256_GCM,data:yulDUkNUtZk=,iv:D6KxDNWA19UaOVcQRStZ4es2npoWnLVs9ceJFlm2gwQ=,tag:yU/x9EIn/Ifg6/20I9y4gg==,type:str]
    CONTACT_EMAIL: ENC[AES256_GCM,data:Jlr8DZS9rpQ=,iv:msxQSHE2c4H34TBgAh7/YUpW2BQNZ+bfxQRqSSNquak=,tag:ew0SEVgDymSDQJwBEZTcCw==,type:str]
    CONTACT_FROM_EMAIL: ENC[AES256_GCM,data:uwlvBHHwKEM=,iv:OIigqhrF7LbTOMFY0Xqo0FZnOlKaVAN22fcXmzRRqeM=,tag:NmDljgljX+XaWwzbIdLYkQ==,type:str]
    NEXT_PUBLIC_GA_MEASUREMENT_ID: ""
    GA_PROPERTY_ID: ENC[AES256_GCM,data:m3gcrGvdJAI=,iv:r+bou8WAKXXcf9SFEKFR/nVdz5Aw4aDaG6aiwML8z1Y=,tag:sVJDFFAxCebJyvUvmr8rKA==,type:str]
    GA_CLIENT_EMAIL: ENC[AES256_GCM,data:bd5ojMLyZtI=,iv:y0ruroNva/i0O3CGPBqtyjQN5XZqjjVjd3fo+4uzGaw=,tag:0kM4kiM/A+ogJ8ZoxyH98g==,type:str]
    GA_PRIVATE_KEY: ENC[AES256_GCM,data:8NYaKnux1pU=,iv:RNBcI8Q6IuqF8Bv54ARwMfRk+PPVlpDviR87q8Z4zYs=,tag:stovspbUcQHuXCtLHG9OWQ==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:H4O+llAXLY8=,iv:JqqG4sQWKq7V7RtYxka1m+JkIuIrmgucyogY46LUIqQ=,tag:ghr9+XAl7kvi/F+bCMKYEw==,type:str]
    OPENAI_TEXT_MODEL: ENC[AES256_GCM,data:AA4bB5mgkuQ=,iv:lLz/DEwYRzllZiZ3+QVZWv1lLDf9MKmUy9eiZdhGqBk=,tag:Hfu6le1bAA9LiWx6Amr0CA==,type:str]
    OPENAI_IMAGE_MODEL: ENC[AES256_GCM,data:oO+I4TqhA8t26cg=,iv:AqPVL1jJjjmdNY8WSNmhZJXd6Cn+jFUvnWOs0d21BIQ=,tag:arL3/KNoyZsYJqIHqLrQdw==,type:str]
    MISTRAL_API_KEY: ENC[AES256_GCM,data:jgyHJW8bkaQ=,iv:jNKYrsYhp7I4a4KJqsg0h7JcRn/lsSQHoYkk5hBxJIQ=,tag:XNZdh+4PGWj3kI3CHdM6/w==,type:str]
    MISTRAL_TEXT_MODEL: ENC[AES256_GCM,data:aRXf9uvDW10=,iv:7uciCiuO4gkAWylzi6PI2sxuMUkAs2/AJ+O4RuMIihA=,tag:tafrkttbu+j4Ff59ziLzAQ==,type:str]
    MISTRAL_IMAGE_AGENT_ID: ENC[AES256_GCM,data:EYVQvdQ5j6U=,iv:bHAwskMXefyZfo6Su0GN7jRQjlkwGzJT1labaulx7J0=,tag:WNbPJ9jfFUs+D2v374tImQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZmZ1UjVLemlCVHZiTXI2
            QmJmUS9JSzNWK0xjZlNWeWRVUDdNT3M0eWowCitoV1YwOUVsU0tibzQzZTg2UklH
            aWpwTk5MUCttN2JZUHVtd204eTV0eWcKLS0tIE1UREhJbTBvYk9OajltOFJEMVlB
            L04zU3h0QWt3eHFQRVJnVk5ud3lka2MK2OP0NQ/AeJ65nbOOTZ5FlMZdSlQ83whX
            yqQldjx5OcSZrNZqjUZGKfcOHeMAbOLp/n97NRk7W//20WR+zdW+jA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lm0sz9afv6fdmpqcfsrhcfvkfcw6rgga20mpplrryxwcppfd6glq959w5j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T21:13:21Z"
    mac: ENC[AES256_GCM,data:sAe14RTUmDzTLTVi2/W2KqJIXQV9+OupQPHR+Wji2dr+BN3eX9EcYkTU274ob2UWJm5IptNjjWM2Psa/Iy2vwbD1CuQ2M8wbQBF74vt2MPISkz6Ja4NVK2ESctLemmwD5nmEujPh0tY9U+h1BjgZucD7obj9GIwyScZJfaR61TA=,iv:3B8HcLzh0xa1Nngvuum+3TwTvQYrraqyiKYrK2214XQ=,tag:UBhPnvFln7MhAAy34kJG5A==,type:str]
    version: 3.13.3
