apiVersion: v1
kind: Secret
metadata:
    name: website-db-credentials
    namespace: databases
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:XjuOaZTtJw==,iv:Yf2l3Au99bKkPWQzngGhEMLyyqfKs3F0eejRVYeH5ks=,tag:Lm3xl9hMsElovxKj5W4Tmg==,type:str]
    password: ENC[AES256_GCM,data:mLRPBN6Kiyr2/IL2jh6p8DG3okTWt2mYDXs97u+fWZo0eFWKZ7InL8N7YNw+m3Uv,iv:2FgkFKErW7rE+qDWZ+g/cKnlSEHD3/5/uf9cbww8z9c=,tag:7NeaTakTJuPw0r2jvxCZOw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbXV0VmJTdGVCdkduWmhB
            M2xWc2loSE9FUU1DL3VMZzdmSFFhU21wSHg4Cm9qR0ZtTUpFeHoyZWJJZzlsN1ZR
            T09tRFRnL1ltcWREK0hzeUx4WnBnQWMKLS0tIDRaR3NaSDY1RHI1S3BPV0NHblJ5
            bHk1SUNIU1g1QnJsK2hwUXZnemRMYlkKJo6XY/J1DeN/eWTydexGPMge2QcPRx/V
            sVxSrYYUJdaLhlP0DtQEUX84F5najvl3gv+Vc/bjEhfOWnTSLBG5ew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lm0sz9afv6fdmpqcfsrhcfvkfcw6rgga20mpplrryxwcppfd6glq959w5j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T21:13:09Z"
    mac: ENC[AES256_GCM,data:qggo4YBbwRnvdMn6VMsnG0A3RzEMh9Pc9DeAeCqZrYR0CzfadVih6FkOXxG4giTwXDZdZSQRYKL1tFcQcAinkrQob5wGjSNbHfZbRBREgFdJyW3AmW7+RB14Z9/sT9knDgrE+uPbN7KLbE1+KuaJnw6UTvxiCX+jIAzQFtrdpaw=,iv:Vw+hOwkoyc1IT8GjH8BJgPo+0ObRuwPIkO5uyDGFWJ4=,tag:oHd7qedgx0spUNddY+YdMw==,type:str]
    version: 3.13.3
