---
all:
  children:
    k3s_cluster:
      hosts:
        k3s-01:
          ansible_host: 159.195.82.201
          vlan_ip: 10.0.0.11
        k3s-02:
          ansible_host: 159.195.81.219
          vlan_ip: 10.0.0.12
        k3s-03:
          ansible_host: 159.195.80.83
          vlan_ip: 10.0.0.13
      vars:
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ssh/k3s-infra
