apiVersion: v1
kind: Secret
metadata:
    name: mcp-server
    namespace: mcp
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:dsgDP1Jkkt0Zli/shQyEiGPSru7T3LutT+CJ1jrPbNVIjiB5+YAdx+5FPALOOIn6ymmMjLIitQhHIpSMtqf+zA==,iv:mewl9f08kOsIJRyWc1ozRjKoN8llJKlHETwJHGmqUJU=,tag:UJvGPs9Qgulp6t1QW/NGCg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZSthUzhHUndmWHFQUjJj
            dHB2WjYxaDV4eWh1ZUlhdE9DdWpJeFJhaWk0CjQwVVlPS0g2VHZUM0FwZm1yNnVz
            SXJ4amQ0OWFzZDdCYkZUQ20vQ09yTjAKLS0tIDJqRElnZjMvM0p5NmxCYTcxYTZR
            S2dxb28wcmp3dDR0NVdHRDBaZ1RLaFkKZWBf6kYudI+VQKTzlxXXdiG2YiJ4hhSh
            muc9tff2m7IZ8uISFxAENS8s6YxgGFmhcX+AciynljGZnQ4MrFuuiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lm0sz9afv6fdmpqcfsrhcfvkfcw6rgga20mpplrryxwcppfd6glq959w5j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T20:08:32Z"
    mac: ENC[AES256_GCM,data:Knkpc2AtS6YwPZbbPgxnUVz504NQaESTkqCwKginR1hBgQ/RsC7+WS7rnCtaQfN8oQHxVnL3fARdtDAjLMFygi8ZbQLh2q+UU1bKbBmAek537nRpkFRNJCLVRBTsKMIBXq+S+kStsvbhqnRJticK89dyZ8zJOG7K2zOI2HGklsg=,iv:NYaa1rIBJKur9Zjg0OzE0xsqFYzh5uI/XMHbf662K+g=,tag:Ez4LFlNlLXF5k8KSwlrsdQ==,type:str]
    version: 3.13.3
