apiVersion: v1
kind: Secret
metadata:
    name: mcp-server
    namespace: mcp
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:INj/j7wzKDiPQdrmAX+10xUrPfPH060HeXBrym9YP/uz8ALNQsapAnRDtrk=,iv:AdkTmYu1e53jp7hzAVrcZXgoBVp9I0a92ENURR7XrAc=,tag:smClU0+gL6tN7AofNENu4Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZSthUzhHUndmWHFQUjJj
            dHB2WjYxaDV4eWh1ZUlhdE9DdWpJeFJhaWk0CjQwVVlPS0g2VHZUM0FwZm1yNnVz
            SXJ4amQ0OWFzZDdCYkZUQ20vQ09yTjAKLS0tIDJqRElnZjMvM0p5NmxCYTcxYTZR
            S2dxb28wcmp3dDR0NVdHRDBaZ1RLaFkKZWBf6kYudI+VQKTzlxXXdiG2YiJ4hhSh
            muc9tff2m7IZ8uISFxAENS8s6YxgGFmhcX+AciynljGZnQ4MrFuuiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lm0sz9afv6fdmpqcfsrhcfvkfcw6rgga20mpplrryxwcppfd6glq959w5j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T17:49:31Z"
    mac: ENC[AES256_GCM,data:B3N1gSKhR3dmVR6U7CJgV7nRsd6iiMg0FPPjSfdZtsH9keqBldgG0xOsvGEYyC+VcEtrCL0DT3ImkVPb0DtSU3XTZJHJFz9K5feAg4/ovfv9INr27nJJYTr+KOZyhmCeOzTkfKk3FOagi/vca94voi4+DBkP9jXe4q51FLpGzAM=,iv:nd7Vs9KtwxNSO+u0GfKaR3KlvQdFeAjlAesvSkwS1Ao=,tag:+80ea1nUnvGj6JxTBBEtdg==,type:str]
    version: 3.13.3
