r2_access_key_id: ENC[AES256_GCM,data:FFKLAih1GK4EM20WuwhWw+gb+FdXYNzNt1eorhTSWl8=,iv:yWEvnPwf4AV0WrcohRXrZ/JKoOVrdsMd/HFhZ0crzvY=,tag:YNoSuLYyZaVLuXl/FNiLDw==,type:str]
r2_secret_access_key: ENC[AES256_GCM,data:fYBDg7/y0rryx6iZtFCorehcD4uMkbvF366aEw7UD1+PmAELBc4SIWpx+RjK2yyE9oCKT970G1Qnf8hd5OStHg==,iv:dC9O7W0EUh8l2SGzo6drPJMUUIEbhtdjU+ZRRc+aYbE=,tag:mphih3OqW67XblAbKETYJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMlpmRG9TNjlDOGU4Nktj
            R3dIZnA1QkUvakZpRUZzd2QvWXp1WTVWdXl3CmZrMDhiTzhvUUU2M0VqTVNOYk4w
            dlRWR01IRnZNcTdBWFdYRk1rMTFHUGcKLS0tIE5yV2ZRcEx1QlBVeW9CeENIdjZ2
            eXJVODJ3cE5yZ2VjUTEvbXRwUXVCYW8KBFBRiFUFdnnp1lorNbKWvMcgrV+qY3A4
            g334stFaucjsIm8UmWcEuMcUeB8WfICuT0ufjYVjfCVnYb5aCjbhzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lm0sz9afv6fdmpqcfsrhcfvkfcw6rgga20mpplrryxwcppfd6glq959w5j
    lastmodified: "2026-08-31T18:22:05Z"
    mac: ENC[AES256_GCM,data:4BpzjlF2bPFvYbPq2b7xKEtvhEr3zYhUOQwvNNac5K6MSsthXi3YkMgsu/nW0FrcsPTNTRuOE23sZewVXFgJSy/gDOO2FGAnC5GtkYT0wAw/r48tBYRkv7L2/P+sMQwCee8Aixbi3OfRJHPbeYgFga5j29mjKsh8951X5/Ialgo=,iv:9FOquW2oexhhyA7/p5LKsrvv4ro3UMxWW276rV8J1tk=,tag:oRY9IdZF/NwrcwGVMIRfgg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
