apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: external-dns
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:G9BfcCCnN9X9joCWhtGUY3NCSuNtXuAw5FbaY7KS9IwMVcm7jZjXsX8Jg2jf3V9OenhKMH0=,iv:T01WVfxmhyrGI9KS+LmM7k/HKIkpJ5ShVyLu+5ifwTs=,tag:JFM/pteENRvuRC3G5diN8w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweXExTllXa3ZoeTRCK3du
            aUVrSWhLbHlaQTNjTlh5TlVTYmhxK3BQazBBCkJtQXVoakdWQndMSFgreDFWMTN0
            SGVpTXo2aHdGaTJ5eWlqallWbFlzRFUKLS0tICtpcnNOdFUwTXkxVVZhQmNZYW9r
            VEtVbnNkenYxUG1HbUVVNHZCU01LYm8KApR95kEQoP7jYAp65JVTLRQxV5mlpg7e
            rAA2Iv5NxbMC/IU2dBG8Ir4RMVtuVRtP/D+QRX8pZTSatToMa1kXvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lm0sz9afv6fdmpqcfsrhcfvkfcw6rgga20mpplrryxwcppfd6glq959w5j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T18:22:05Z"
    mac: ENC[AES256_GCM,data:ue94hfBeEOmnsnOGw2EuRXxmx/WQmdmp3d1YGVW0cvmJDs94uJVgjkSBZEajCtD4+xJdk4PLoeOsB6V/S/i05ZJ+Aa1F7ABVdPW2MJw0O0hQS/wErvmQwLTKCpjhWnI62MmOLxVunmHmvwMyLVPEcDc8K1uArS1hrWG/7SeA6AM=,iv:TQLwj24J99Pl0gDUF2ZIl5ou6fqqeCsCDnLGZCgmVZE=,tag:MRNER1CpFYVdmmE05d1T6A==,type:str]
    version: 3.13.3
