apiVersion: v1
kind: Secret
metadata:
    name: mailnexus-secrets
    namespace: mailnexus
type: Opaque
stringData:
    AWS_SES_ACCESS_KEY_ID: ENC[AES256_GCM,data:FphbTq2dPj4nyOTnvhkPycS01jA=,iv:AIgq3UymmICjIzkxj5BfmvDaEcHlHmQVauRhXAIwnX4=,tag:doOuDSrAjnFle6TSV1SzfQ==,type:str]
    AWS_SES_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:6+vEmdF3SoYGAjcWejvcE6+jbg7SkESNiORrtsYF01E9QphoTMD8IQ==,iv:91fiFIb7A3apvZrpnZkiUVwUDxOssfmR44QHGwlkCco=,tag:nOV7TatvhnVkgmyP/5JuiQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:5nAJWAlfeCo040JpzHfVbhqlHPDf0+KD6Wh4DPA9bfBgv3V3zaG2rPKXRT6Fq6vxkExb9AhL8Uq3ShpsDjZiYV4V0Q==,iv:gT4ddk8W3yl4PjgeGL01nOdsaSUIp3Y+Ycgqgv3Nzrs=,tag:OmByYlD4zbb4wDNDroRWxg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:vS/BQsiLZOZZeIHhprPtUPCxaHpxxyfxKw23MQ==,iv:Y4wVKYr4hG6QQTldZSj+aTtjI1EqMyUW6N3hYXBcCIs=,tag:XHxnJc9gseXPO1HVxnalKA==,type:str]
    DIRECT_DATABASE_URL: ENC[AES256_GCM,data:6oxHrADsZhlIw58721mBwaiqtj8Uowv07/jebWhS2zSNGVWVB4XuyZ1hUkBZqUqysEtnUXlGry6vb3Gq6ikYscgphg==,iv:hSNUOwHR0FbpMMBtxdcLVLVaBuvxnQsgsiWVnwB/a90=,tag:/rUTC5SmXoME4sCeFphRWw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:8dj9iVYTqPlBJnDmaAM5vRovDFCbSN0REp+9bdF/w2hkhuNXYvKFEHdF9fs=,iv:Q9GbR+zS3x0jVgl8a+wQEV01yjxhwchiDPcWEuPI3Ws=,tag:2brjjJtnh0W6bvHSkSBriQ==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:x2qbAexA/wOjNJi9UJ1zNwsNaeycPCnoSiWL6Udhi88=,iv:0W9GnG0itknV9s8qhSDv0t4gO2EK2fSupbPQL4U5x1g=,tag:qqtrq/g5tmXCGNAMnZq7gA==,type:str]
    S3_ACCESS_KEY_SECRET: ENC[AES256_GCM,data:xmnHV4o56KnB2a/TSQ3GyIiZubeqz7NfaWW4rFfw4wBxoNhLkrRqUbyY/ZB6ISGb4M5VHji9UH/J5MzEbeCr2g==,iv:0J7cDqY0btaELJ002fvUj3mS2ea05Pd0ApNpQ/FYoQI=,tag:T5zYgW3oCqEVOxFChtVPRg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNzM2R1pxcTFMNE8rbnBH
            UWtid2J3UFQxR1RPOXhoTnJ1bTUzZUFnd1c0Ckt3cnZGS1BIS0FXSnlIU0E5TFVR
            eFluRnZUc0hBTFNZU2U0U1lwc0dEa0kKLS0tIGx5TTlNUWtMZDFLb2xvSmo2bm5l
            T0xFS1dnQjFLdVBENUxiek5FTWpPM3cK/2Bas72i8iwEK0tJ4/TH5h3LQWNlWdyi
            A+DHfcFTziQfAABkcJtmZcMMcn1AfXFYmgKnuyPBlodNDMg+pbfkug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lm0sz9afv6fdmpqcfsrhcfvkfcw6rgga20mpplrryxwcppfd6glq959w5j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T21:09:22Z"
    mac: ENC[AES256_GCM,data:nA73NHBwL6/r/yO5JXYfaROtlAgOuFF0t1+d0ZS3ZHYo6LjkzfEUeGiH7RYkW33Bx1m2Pfu7kZYAdRODxIkRVifxEY6LAOO+mR+BjZd1eLNgIwxP20rPWnkjbaetSWyNEkLgQ8tmARDhGuD5Q9guC58Mv8gp0Fpny5Y/n8rhJ+I=,iv:dpUgnSCHJpmJBw01J1x7bBFSHKj/4G1HH/IBKUr9ABo=,tag:duWM2QTlByhkuXg5A4tjhg==,type:str]
    version: 3.13.3
