apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:H1bW48s=,iv:hwUdcC+tuuaEbFGSMPRJ0j2wrEM2/HlktjqQtZw6RL8=,tag:PsPRPC1JfoxKdr7p44wC8g==,type:str]
    admin-password: ENC[AES256_GCM,data:p+HktHRWA9XYTJzA8fJn5yin+VAOsTOzILwWaF5WRtE=,iv:g6UZXQi90o05SYIF9P4nUgv2nyegnfh+zXtbEzHdQaE=,tag:ovPKwpcJXTaXSYhorrpH7g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvV3VJUVp2SHhoWGlRNlhZ
            NmFZVlhnVFpQQUNKcSttVHpYcVVLZTB2UmhnCnB2STl2d0xVRWhaNG5SZ2lIV1BN
            MmlIRkVsTmEwWjZFaXNrNTk4ZWRvVzQKLS0tIGhzOFVRbWdtN3BEdDN6ek1nV2N0
            UmdVOTd3STVPazRENFlWdXdBYXA3VU0K98EpxL+O4X/NexEEWf4aeqhfhOw2Zelb
            /jJXe8/7pkBdORTvZGppNpjh7oAcp+wE32pC0NCQezEQJVfRRZtZPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lm0sz9afv6fdmpqcfsrhcfvkfcw6rgga20mpplrryxwcppfd6glq959w5j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T19:41:36Z"
    mac: ENC[AES256_GCM,data:cpJOpwpOh/UuzCkPXCQKuC5rI5bV2bvRkwc3UzVA/ol8gus9VaiKtveDRjUl6OQAh7AfCo4vE14nrA9dlyUQfnEIskpYnlERPqs7Dn+m6XhrZFD+8iiwxd5NN1WQOEmTD174KGVVF6ORu8ItXSITp6ioI6lQZ2eFrDotzrkhATk=,iv:23kG23Uw8XAihinHPrQg11Mi4KMb56URgKLBHfFQh24=,tag:ftlqtPlxeeFT8PPQMX6HjQ==,type:str]
    version: 3.13.3
