---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepos.yaml
  - victoria-metrics.yaml
  - node-exporter.yaml
  - kube-state-metrics.yaml
  - grafana-admin-secret.sops.yaml
  - grafana.yaml
  - uptime-kuma.yaml
