apiVersion: v1
kind: Secret
metadata:
    name: gvasiliourolex-db-credentials
    namespace: databases
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:9XakHARrYMreOoY5b3Q=,iv:c+0QUjp1oMsnsPE7MbpjpxjAdTMzPhOueJay0iS6vN0=,tag:u8VG/XZqxha1umKcpw4jEw==,type:str]
    password: ENC[AES256_GCM,data:cwvjYwCQkzeEut+bezMMNlrIOY2YQeVXcfc7snBSLH+LJ96jKFx2rs/Ahtrxlibw,iv:UtTjmgiuCRdaLcfYTFAoJR1lqT6/MJEkg9IQfqME4dE=,tag:ODA5UyFws2u4CkLBZmp1vw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Q1d1RTJRZ0I2UTlNMXcw
            QjJTNWM1K0JzOU9waUJEakdMd0JhVW1LamtjClRReFIyNXJKVXRzcmVlTU1OTUhm
            QnE3by81SkJ0Yis2b3RydWh3RUxDS0kKLS0tIEU5L0xvWXFUREkycmVwZm8wdXNh
            Z05pWStLVVh5SmF2eTRmcm5QYXVsa3cKhBUdB0pdHQmpEYCY6IU6A/KsuhEXTCvF
            5RTJuJauDTjKOCFoDBirl9vg3WstClBYUztjRVDnJ0y+OEN2Gq0HrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lm0sz9afv6fdmpqcfsrhcfvkfcw6rgga20mpplrryxwcppfd6glq959w5j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T22:49:59Z"
    mac: ENC[AES256_GCM,data:9VZcPs/V4QjiKaQwD/CjdP5IT5VtIywKfzKht8njzR8h1iW+8nmPNPchHboObthpIGAcg736C12gsDeRE8U5jvjENUVQueuY6p3w+nqU8vJqH0Y8YEWZdBym34zRbpl+fXt9zcvpj/cJkfhnBeC2yXCTg5vjI09mzV7O76zuzxE=,iv:jbQuhq3ZuKP/Xa1DISpFMEPldMRRDVdjp62b1dbu9Uo=,tag:l6k4EqGGxnNBkPOucevppg==,type:str]
    version: 3.13.3
