apiVersion: v1
kind: Secret
metadata:
    name: gvasiliourolex
    namespace: gvasiliourolex
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:+TBKBz+9bjcpIHdmOMedzDeznr6oWRrgJpkNHF5e1N0+eqOrzC6+VJVrdwi3Y9f1PrhLbZFGhNAI00CyBMVSVxSPZKys5bVAPP+tEtoTn0ugWJJw6GV4Q/mvY6Evlz8yI3JPxcvE94dstWA/vihCyg9+HlGo+G5S,iv:MlOxhEZ7n6XYUaOKdUdoDS1VJnYbtgD1zCQXKnsbkGU=,tag:n1EEJcxbp5GNgSAIV94e4g==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:Wbh+aHb/3bUaUW4eNGy3ZrCGzO69v65MG4rCsLGJLEanzmMRSS12b9bkDP76EFsej3xbd/KxGsaU4F65AUtKbA==,iv:fGTJIs0ZVR+Zs3Vpjlzt+ZLIY+7soqVhRdJOXS0zTLY=,tag:9HATPRbrfA74aFAfiapC7g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETlN3dlZ0M1ZsK2psWmZK
            TG9oY0xnWk42dWRvUDBNWUZPS21HZ1hlYVVBCnJveWZQY0JXUFNjQVlibU9GdkxD
            Z3c3RVNOZFdXTmtYajZGa1hJMmFNWUEKLS0tIGlJYVJ5YzNMU1dLaWZEOURKd2s0
            QUxYOVpFaFdMRCtqZVJYVVcvWWw4d0EKraQPTz6URghSYmP2vTeIkAJ/z819xy2R
            B+I8XCAcOJqNp6p2n/q7cXk4ipfl1x/qWw/3011OGEVcBeALxLaPqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lm0sz9afv6fdmpqcfsrhcfvkfcw6rgga20mpplrryxwcppfd6glq959w5j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T22:49:59Z"
    mac: ENC[AES256_GCM,data:SPrnEodBEcSnwz903vx7nnhUpt/zMUz4VLUX3EXrnM8JA3/XCC/P4SIGlNiHFjXCZF7+ru5DVqpaML1ztT8XTVjA8KcOGERpWORib+uWOzE6t7BWcHft1QefO06Qp/kQU71m3Pr90CQVfwSPnv0eQCmrP9bl3a7zAi66ZlSvq1c=,iv:MhLQGFffYhsFjCeLNmQhyn2/KJnIyoCtYIWj4lOsf7k=,tag:Qir3AuPPJWL8/bM9JkZJsw==,type:str]
    version: 3.13.3
