apiVersion: v1
kind: Secret
metadata:
    name: signwise
    namespace: signwise
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:IWJyaoc5ECj8/V9SLWyYHlItgbUQL/g+k8s6wRjhC2C3w4Bb9Whiy88cmH3vqytXe57kHY1Dx2bZfbqvaZwxJ9iEn1+Acebzxx5nIAJX5/ULNAtHuwJceCNqBfAQqcriuNoFKQOqhC0hHcKs,iv:wzMbE46ivU0zNyakY/Alo91UXQ+kf9h68fo3OhcyPZY=,tag:NMC+zWTZ8l2ydRBt584Bnw==,type:str]
    AUTH_SECRET: ENC[AES256_GCM,data:IdNXKwHaAyiKJ3usj+4uQzsfCtz4f5q4iscdxC3TcMsyEeOJwmWLobhafUW7JMmdvP2viozt+CPcEo/WO4o4Bw==,iv:ZP7cmt4uuqTauayZJ3v54e0gqeXnjI/ygPIHecAIyUA=,tag:LWpdSCd1PbPpwUhx/WDCzA==,type:str]
    SECURITY_SALT: ENC[AES256_GCM,data:0MZllqsnqb+V1niziTMaaWy8Fo0jQP1GmflV/DYOe2KtpgDXba3ZTySsS1bdPYzn,iv:MuCifvY5rgGkfUJyABcqVgzTfdw07WgvGihFTntfi9o=,tag:t5l2wq12pFLXhguRpRx7bw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVL0JHL09hVHRoNXcxQkJT
            dEtLYlBtOHdlR2Z4TWNGL2ZBdEFqSU5YelZjCmlDZWk5SmlLMmo4ZCtCWmdKS0JY
            Z0xQOWY3RFh3MFJjS1p5b3hleU1wenMKLS0tICtaM3gzallJak9qdHB6eFZMdDlh
            VjdNVmlBWDA5aGxCSXhJazJQcWxCTFEKuRNQnvHmyw63mwvjmoUo+LpuUF8YcnNF
            pDYPrTxAWHQ7i/Xm7SEGRuApYQ1K/1mpAldDytCDja7VsyDX72XcWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lm0sz9afv6fdmpqcfsrhcfvkfcw6rgga20mpplrryxwcppfd6glq959w5j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T14:39:20Z"
    mac: ENC[AES256_GCM,data:rUKKsHlasdfMpoF0v9V3nn3y1WNJWlCJ+95sFEUT4hW0R9MX27GLXiY7sof14Tz8pCljj+ynSBJ70Q5dBa8X5Tl1jXNeeLYjEfSrDhj3OtKGLKkAOQAFvjlGF+d1zA57cshuaRGyIMoSZp0+QnGzpUl4zqDHNnc/qUe/m+JDlvU=,iv:oapBRU3s2oQbwFXHGV7PYAIPuzdq6Lc0ePXZ4wI4kx0=,tag:2l3ZL+ebHG87zrXRvfz3Rw==,type:str]
    version: 3.13.3
