apiVersion: v1
kind: Secret
metadata:
    name: signwise-db-credentials
    namespace: databases
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:gDeJFFrStPk=,iv:+l2IGwuQ//vsD2vhdCS7iqDFfUkDdWZT3EYgBEEW1k8=,tag:YxNm4kVv/FWgl3Y68MOJPQ==,type:str]
    password: ENC[AES256_GCM,data:tHt2XqLBBgED+5iXvORNj77jI42qtcOlHRVWDww12CeN8Grgh+h/U5EfjGEeV9be,iv:Newh+06D80xYvrq0X8sEoNpVOS3zt0ARk/dLKSPNOLc=,tag:oqFEv5ZkOUTNxkSR3bnZ4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWTh2eTRjVWgzOWZ2aWVS
            aWE5QkJtMitxL2hMVFdkYWxWK0Iwck9LdVd3ClQremJVeWs4UmpsbVJQNEZDTjZu
            WG9GQ2lzOTR5UXV0Um1hWHhzL3NnOFkKLS0tIDN0d0FwaWZsYUNLUWYxTmZFdUhY
            Uis3elV4TjJzV0lvQlovUXBwakNpenMKbUTvmexStFPNStOnspFBrz2L1tdkk9KK
            nPu1KIK5zqioRVxjcX5WGTIhiveeczlPJrHu40rkKitdt0Zpul2USg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lm0sz9afv6fdmpqcfsrhcfvkfcw6rgga20mpplrryxwcppfd6glq959w5j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T14:39:20Z"
    mac: ENC[AES256_GCM,data:UL57b5rJwC/RwL52HbCBiZE5fSRtBz44waOUw8d/z2ORIkhWXnfRZiaHYq7s3otDJjRn8DJ+x6NzI9T3g++OylakrKcdsDDbs+oeQWGzR0/sVR8z3mbIvupjSlwY7JaR4BnCdT7Dr3pDPR2cOEhy+m2mU4IQYReyLNLSCeUJsMQ=,iv:KbyVHTwR+p7K16MC5ELuRHQTHJT23HPkq366IqCXFi0=,tag:cqT8w8lh9UgE7hm/aGzPxA==,type:str]
    version: 3.13.3
