apiVersion: v1
kind: Secret
metadata:
    name: signwise-seed
    namespace: signwise
type: Opaque
stringData:
    SEED_ADMIN_EMAIL: ENC[AES256_GCM,data:jgx3u2OCsqptBAofDiDMBEsi3rVqYA==,iv:VCjCCq0ctVPMvdQE4VZn7h+lMO3aWEchr/GiolmMu+Q=,tag:IIDXn5f3MZFDcC8dQ0+NaQ==,type:str]
    SEED_ADMIN_NAME: ENC[AES256_GCM,data:RUfYkPNEaVQk2PeStPUiI5Wx20s=,iv:dbQl/s1EnfcnoilQyRuXwp8GxxtbdJng9CoIN8+FUZU=,tag:bbRQQwCpWgoHo8Yf/twKTw==,type:str]
    SEED_ADMIN_PASSWORD: ENC[AES256_GCM,data:PhjXsJWBPVCLmoIrxXmcoobNlSxD7Sig,iv:Reaxf833dZuMX/brl+Kv/51IoonNuAEXQlw7s5sYLu4=,tag:2m3rsEmLWTg6FylMKYx4FQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWlMxTHprYUhhbndOYU9n
            MUhpQitRNHpSODBsWWp2WXJkWEJZcVlFOGc4ClZjNjRVV1F0YWROQXlzbEdKdUZS
            Y05UYnBlNkFhaHhldllJdWpGdUlkOWcKLS0tIGZtTzZlOTBQMnF5em1lZHJJWi9X
            WGR0TUVMQytFeFh5MHFvSHhTSlpmSkkKps0m7Z+yVuhPXoVOMqIFGLcvN1z85C6l
            JMReeq3RjWILKm59v1DGm5OrY2FChW0tODI6Mthp+rN3nn+Bcdz40w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lm0sz9afv6fdmpqcfsrhcfvkfcw6rgga20mpplrryxwcppfd6glq959w5j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T14:39:20Z"
    mac: ENC[AES256_GCM,data:e9ag3+9P9XzF7o23FTQyg/w4zG0fzEbq8mFi/zLN0F/bbWVo5NTU7Ubo4GNh3j58NZ3+0P9WjJe0mb9lTTcmKwCngHTEr6d0oDyq/PGGKrfGZZu1+Aa+8DSSeUF+QtbyXRbpPCQDv1bgyXbKIAMdjIHL0C1sOOtsi6dLgSqKaS0=,iv:54H7FCK7XI//kx0mAD/DHHNMvTEC0/7lz4+c4orh6mk=,tag:5+eVevgAxLELjCWwsPBfOA==,type:str]
    version: 3.13.3
