apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull
    namespace: polyedge
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:ExksCY8I67HCR8smZuznA+EGcb6wsP9PTwP5LqQCkDnFRHD+1LHrtPbl9bUV/wDbgfPpYuaRfSvgaCA2ICEwMkGNJ6dskMbXXgKek/13iACuEu4LkFCrKq12aRK5k19YYn8Qrsj3vAcDHNGaUIEtM7FfAQ1zVGNCFLSmcLcBN+TFgcaazVmfrUor+ED7+jf//hnNWkMiswyIwQX//Ab2OmuGHO43EDzRIh8B7+GShLycaQJgxFD5veU=,iv:luHrPSiSP6FxHiSb1OPvPr0q77I9M7JpTN0DMstQMvg=,tag:UQ/rCeKdq/s1ThordVw7rg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaR2JaRnlWTXhSSEF5bVZN
            R3FkNndkS1Y2SUhjYnoyU0tpQm1DbjVXQndBCkcxSVB0Ym01RmhBSFZNczhld1k1
            aFJ2Q1B2L1pwYkxyY0NKd0YzdEloeXcKLS0tIDJmNGxkL3F5cTdEOUZnR2RFZzMx
            VDZ2aXNvbVQwUzBwWVdIekRiT1JOUEkKkKz/44gSID1T5ubhIzlZfn9bWGBpcXlC
            lQ2I4S8ZVkDs3XH93/hKC9jX65pdxMk+UtBbYB3dGcjfEKxTHKY2+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lm0sz9afv6fdmpqcfsrhcfvkfcw6rgga20mpplrryxwcppfd6glq959w5j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T18:23:58Z"
    mac: ENC[AES256_GCM,data:EM6GRpOsw0fOLbUiOfoW+6DeII6BDKcncpt1w1/+9DGp7KCUrCEKk9+QLKiQ/SD//Y9iClwZ+jYxuieg+0R5hLblT6+1jG9pO0aqh5tlFZeBONogsDYD8d71NsE1lzzmx8qOkVhxSHybTtn3+NvAWLJeF2R9YpSKSll3I7CkBZw=,iv:XOgd8nD+Nf8S0SKSYBkb0qadg7ZzmZ7VrUqtjwI5rig=,tag:imJlNyki0OKtwFMO7px9PA==,type:str]
    version: 3.13.3
