apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull
    namespace: polyedge
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:+V+TIIBJvOxpeJHjPvAiiP0SRu+oPv5lLDxFLk2DF57EqCOJsrcoltyKRDSRuhvgqYOn3BYGIjxgND8/47kXAm4CjKwlERSAArIjfoyuGFQDiuCHKjcKWi3rbwo0Tgc/R5yrrd9e4CPhG3gtBCyvWypAd2bqUKocygCIBKpClaXSZ85C8TbBeBM128AtIaoiXUgHABcvUbAeqUrk7h+T0cfL+Q4Hbr3RsDdCNE5ki91XszDilZAkSt4=,iv:WP5QmPNsvbpo8qOvKt5m1oJEUbRqBlQq1AeTZKdF1vk=,tag:n9+NtJh9TC+gmkBWt+4jHg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMERDZ0VTSVZVOThmeE1N
            WWtTWFRjbTFWMWdsQ2U1OU1OTlpSOGdSTmhrCjRDdmw1Y0hxL1BzdnNOSFJFUSsr
            dUsrdUpiZDF5YTVSR3duSGIyejVIMm8KLS0tIHBKN2Z2aEROKzk5cFZRNThKK3pn
            UnFXWDg1N2Z2TnBRYkM4eWZ2SzFQN0EKXVevrQSEx7/1+dnea3WovlQF3MOlafU+
            Ece8m2y+lDL9h5f/3ZfwRK0/WyxSTAur9xAzLhAH5PfyHOFUE8BzxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lm0sz9afv6fdmpqcfsrhcfvkfcw6rgga20mpplrryxwcppfd6glq959w5j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T08:16:29Z"
    mac: ENC[AES256_GCM,data:ICay3LFdz2iuXIXTzHp8PyxPlumrOploTnT2Jn04a4Bry/egaQuq3YSXkutG+38M6GiuTTqKFpIsgFdXSH3TxjfXpaPtH95edu92RJSFvumE/pI+j24K8x/aXySAgixaZC9AHMNgur3efKhRKHcc4nIJm5eL9eU21fy3PXwjPe8=,iv:rFYiwhvWkB/u2QG+614tkdHANF6q/xJYinsGfjC3MMY=,tag:2x7tm4/07huPRJSw79zifA==,type:str]
    version: 3.13.3
