apiVersion: v1
kind: Secret
metadata:
    name: polyedge-r2-credentials
    namespace: polyedge
type: Opaque
stringData:
    RCLONE_CONFIG_R2_ACCESS_KEY_ID: ENC[AES256_GCM,data:NYEHnJHct320Po4Avg1k8CRFPR8ZZsktTawO2O/YOg8=,iv:eYPIewZCXG+uKAyGLK5QCqEyNbTSVoQn0Dtzii3E/Iw=,tag:Ix7IQA1gSyaCHo8LgjDdIw==,type:str]
    RCLONE_CONFIG_R2_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:/IAw7IXsSRfl5VgiTQIu8QLQtOjeZEqVudqO7aWOOd6GAtZiWQwS4/yjFsr2uBG3XHzJcHhJrc+z7Ud95SGUqA==,iv:ge6H7bkGcm/evrcmfO/phrkHcYIFJXF1UMpp0CJUZgk=,tag:wcO48S7ZTUoSCeNLBvh6lQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArU2tPNXJDOVpPRjJlMmJh
            V3hBd0k0N0hRZzF5ZEZNUElnNkVUZDUxQTJVCnM5UHpTYk54SWlGcm1xNngxMW5x
            bzFTeWZ0bVZlKy8xbzU5SlB3d28ybmsKLS0tIHE1TXRXQVVlQkNzVEdjV3NZSVJN
            b2RLdWlubWJPTzdYTGIzQjlCRlNJM3cKg8+ksbgROIZNL9HGlivoxjxUmkHcIAfe
            QglFU1tr/81GKpeRxEwdEFsSQ7oSxz39oibbbg8En2SlrV3oHkOoNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lm0sz9afv6fdmpqcfsrhcfvkfcw6rgga20mpplrryxwcppfd6glq959w5j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T16:34:07Z"
    mac: ENC[AES256_GCM,data:JKqKnq5zKqz8WV+uEmu66LbJeD5Q6yKaqciHajJGDZ9M/2FpA0DhC5tyKSRXdN5fMaB0EOpXy2+zgJSHFJZvDzyTkdhcezPI/mj7uszht4R1VpNRV1Nay95QlAa0DZi57UweP2+RhToNiTPwamk+JQYlKxWiVX3itzZiVU1ydbc=,iv:IO6QNEvSg21ZrSV8qRf+Gxv/gLv55PGzrmi16poG/+g=,tag:EDQNh4dLp1Suw4JeHUThbg==,type:str]
    version: 3.13.3
