apiVersion: v1
kind: Secret
metadata:
    name: polyedge-r2-credentials
    namespace: polyedge
type: Opaque
stringData:
    RCLONE_CONFIG_R2_ACCESS_KEY_ID: ENC[AES256_GCM,data:NYEHnJHct320Po4Avg1k8CRFPR8ZZsktTawO2O/YOg8=,iv:eYPIewZCXG+uKAyGLK5QCqEyNbTSVoQn0Dtzii3E/Iw=,tag:Ix7IQA1gSyaCHo8LgjDdIw==,type:str]
    RCLONE_CONFIG_R2_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:/IAw7IXsSRfl5VgiTQIu8QLQtOjeZEqVudqO7aWOOd6GAtZiWQwS4/yjFsr2uBG3XHzJcHhJrc+z7Ud95SGUqA==,iv:ge6H7bkGcm/evrcmfO/phrkHcYIFJXF1UMpp0CJUZgk=,tag:wcO48S7ZTUoSCeNLBvh6lQ==,type:str]
    HEARTBEAT_URL: ENC[AES256_GCM,data:GYA2aLMAWDvoeUezO+hJ12Y3RsKPfuLEed8Ni/YRjG4nH+76jhr9kIFR9HfLGsHeg2rg2FleD3dBPMh9pxPhCT3bv7rrwT8kBj3T,iv:pEx2omtYAhFifqoM5qB8OTx69ia5W4yXrmpCvF5mAeg=,tag:iKLEweu+PgjOCuo7ucNSCA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArU2tPNXJDOVpPRjJlMmJh
            V3hBd0k0N0hRZzF5ZEZNUElnNkVUZDUxQTJVCnM5UHpTYk54SWlGcm1xNngxMW5x
            bzFTeWZ0bVZlKy8xbzU5SlB3d28ybmsKLS0tIHE1TXRXQVVlQkNzVEdjV3NZSVJN
            b2RLdWlubWJPTzdYTGIzQjlCRlNJM3cKg8+ksbgROIZNL9HGlivoxjxUmkHcIAfe
            QglFU1tr/81GKpeRxEwdEFsSQ7oSxz39oibbbg8En2SlrV3oHkOoNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lm0sz9afv6fdmpqcfsrhcfvkfcw6rgga20mpplrryxwcppfd6glq959w5j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T20:58:26Z"
    mac: ENC[AES256_GCM,data:ty5PNYGXlsPEiPn0AxEHNSvUwHNAYuEvJf/AxkkAlAblGgoevuhHL/JTLaFGJGMM64UZ3J1KrcaHtFC3jRcuJP2FBvqz/QHRithMRzj3+1pXJI/OoLPuwGx8QQBfgBG973P55dMlcmNOJD70R7XsuY3hFSZRPXUkNlXpoAM0HHk=,iv:xDfB4TuQms+SSt7kX3rLMDpTpFLubCkgg6jNiRWG53A=,tag:ukjdPx5cNN0eXNeCZmCuDQ==,type:str]
    version: 3.13.3
