apiVersion: v1
kind: Secret
metadata:
    name: executionlab-staging
    namespace: executionlab-staging
type: Opaque
stringData:
    DB_USER: ENC[AES256_GCM,data:bkqALvmqnAdG8RMFCnCg/05SYd8=,iv:feRTV1paRYsWYRetemKuGOHqFAeU1QE3GZ9FftqRPuc=,tag:LEdHsXGq1/uaMM7qvr87Pw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:VvCcrpq2qAW9AuSZZbd0mh78Sua0M/bW8dhqyarhNb4=,iv:ZGWku7d0mT9lD3AXlPsxWf5pRDMYPq9cc3ZeegKvDJ0=,tag:yDgCr4e2mfez8J90EDUzAw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:Ru/GnUOPhbyGDeMngykOvwAS1Wc=,iv:PtrKJ/kFCL8FOXVYzgK3m2v1sAamvy8+UdcaBtEep3U=,tag:ltpSkHvxokfOckx/+6yUaw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:vTIpoUk5SsP8wueg7qPykCHqbAn0VY5j55bvD5TtBbw=,iv:9rX5LfV6/JtmFBm5kWYnVmJv1BvRTjSg0/VCgDPCeDI=,tag:B6YCqMEd3J8OCzopF2oPDA==,type:str]
    BOT_DB_USER: ENC[AES256_GCM,data:w6E4YpSzBl/Q5Pxu+iaUE4zEyf8=,iv:UD2QR3Q4z46SxlQpt0x/7+N2xac3hrz/ZWIGa7H02hQ=,tag:HMVhZTbFC6CcGU0EZ9U1XA==,type:str]
    BOT_DB_PASSWORD: ENC[AES256_GCM,data:VaQBuW74R/ndyepaZgOQmpRlpo7nvCZpoNvJfwaA5kE=,iv:0dkYx97xwhfmRkosN3uCsKrJ5Uln2ekxiwWt2rtWB+0=,tag:N5I0ImgCzclDk0Owlwtfqw==,type:str]
    TASK_DB_USER: ENC[AES256_GCM,data:/OavTTUoPXKryA7ShrG/S8W0Rwk=,iv:EZzVUufq6tUr5xgd0nfPMVSPWw07tXh/8qVZUhp3FIk=,tag:UHdX43ynHqm2g0ak94YL8A==,type:str]
    TASK_DB_PASSWORD: ENC[AES256_GCM,data:dJc1r22Tn+yMub2cK2Fp77iF0/6DnC08R4Jt3flaBvI=,iv:7Mvkai75G3fMWmXejJaOBr+uEKjs1xg/GqUQPD/VYus=,tag:qbmXYvFC0OoYBsol8E5/gg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:FBQ7WsekzKRNUoXsa0G6m42dQLH0+/gIdZ7X8V8SqneclvDhHJ6W0BO12FB4se909XfmiYRFjqZ2c1xa1zGQoXvBU35RQc2q5wEh4D8LdeFAcs57wFHD0biQh2m5lfAvqKY/y9lS6MQ5y5Swy0blU/8MPLs+1BkEjxDb3Mkn+yzvcPWyrcA9XdmcKp7icZ08Fxj06Scx8WQw5d8=,iv:93/UjfVymYxKCDe1L4wYJz2XHKFKneXE8VEp6AHW9r0=,tag:okYSKclLb6a269gW2xvhtA==,type:str]
    BOT_DATABASE_URL: ENC[AES256_GCM,data:nves5QSJbhl1cS0MPNhDltosOQtgGeeZJ4srX/OIa33gtHbf7YCzxHpXAnfYm3gYBzrDWpex0+2+EEbZ8Sf5TEawLlrcKtqUGsWV2r9aFtGBLTszhkWtxvJCSU2PBcMmQa7G/5izhGgvLta5tV5iafD8LLm7qlN2X5Z5UPK0tTfm5a8w5rmRTvPNWD6VskHoNP+t0PA9kkNPt1i6b8uoOuE=,iv:GLP6Gj7w1zwcguFCQnaAnc7RVJrHHiKRENeOidaDPwE=,tag:HzJGLJI+d7K42LTkYuGNEg==,type:str]
    JWT_SECRET_KEY: ENC[AES256_GCM,data:Zk23w6/pW7vFyzE2BWDqF+vUPFVYGIX0G0drwPWQY+zwZzowh/Wq0MQDPFRqsdM2,iv:X0fCikIzIETm9jImy57FBxXumi6iVSb5ZzSfLv8kFGI=,tag:1FmaiNYyjsRUdiYiNxVeaA==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:Yw+wHwn+XBgYakqradTzWyacZKWdHp0vvQllJ7gnAYheD1Id4xRloIVKD1s2MrRt,iv:SPNc2Hs4jpjwaGpwIfeIjEtjZEJ07VSruhJvu73UKaY=,tag:9wPRHoIeE1EL5swCsbp6tA==,type:str]
    BOOTSTRAP_ADMIN_USERNAME: ENC[AES256_GCM,data:/Gtkgoc=,iv:sKuWl/BU0fJ0nC8zHqQqjtz5kmQatCnqcuyuQRZRiuw=,tag:QDpbcuQYCQfJeSw4nJ5ABw==,type:str]
    BOOTSTRAP_ADMIN_EMAIL: ENC[AES256_GCM,data:NX2CeEfz7aQAeJTWw0VOBwFLU8jB,iv:ZyooyFhcROprx0Y6gDPqw+zfnoksOlpP+LiAWbfTNPk=,tag:olm88vGIEQaWoo9hiSKECA==,type:str]
    BOOTSTRAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:eG9oTBWLtmY47qcT04Bh288RAvA=,iv:iDTqsmF60Bn9qWrHPwZw7mgDEJTqUKbPk0EXvtNaT7c=,tag:9kZ5UtOuNx5YfqRaj/Ut4Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eXh6QVl1SHMrVlgwaWdZ
            bjNtQjIrdWFCZnRnc2dkelR5K05HU0x4dUJJCkx6K3NiM0poamhncisyUWRUbVE5
            QmExK3BaMkg0MUZzL1hiWm9PSW4vZmcKLS0tIGZWaHRxRk9qUjdsa2ErUCtTVUZ4
            SXJLNEJ2aXMyVk80bXJpSXNEWkVzMTgKuuI9Yh0wWJEw1bHjTBDKNblOKHfqmR9s
            8ePMT57QMwzRg4/3QFq5RYWWqWqP0Zv7W6x5rdDdjLKxpLNWrIEiEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lm0sz9afv6fdmpqcfsrhcfvkfcw6rgga20mpplrryxwcppfd6glq959w5j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T01:00:59Z"
    mac: ENC[AES256_GCM,data:fonLD2HlT1Dk7VHXqsE/h6H586Enq44HfPeueXZHUwZjktbiuyHG+qttlJfRLDw6LehShjA0PvdWSXBDuWTt/qFS3mqREHEQfOffvYq18NHpKb5qzqRTM2+3PIXmOY9KQa9PwFl/Ohu01MaD1w58mpZ+SmVKJR6xxGuHmD3Rbro=,iv:y553ajw4i352/9gB7Kk7xVVufMYcg3g89IKPM97aC0Y=,tag:dJzxF12BX1IsyE/of0zv8A==,type:str]
    version: 3.13.3
