apiVersion: v1
kind: Secret
metadata:
    name: executionlab-staging-db-credentials
    namespace: databases
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:WZ83wEge4p68RoDhQOl5+8pgVbY=,iv:goaW6Fa+7AXygKroZ9sSrlnQXI6i2g3SJxMNQk5bit8=,tag:Rk+/EcSwwSzIl7JtGe/yZQ==,type:str]
    password: ENC[AES256_GCM,data:LYIlkOAoG8JPGcDoLZVF1s05c7aMnw1boilWRXhcDFU=,iv:1X5aNwaqJhG3u6yk+sIOVQpxvGexraKxFE0q2syopzk=,tag:kC6tFqTmpb4fwyYArwe94w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbGhUUHJmWFUycEFxTmdv
            cnNsT2p5SmNPT0JzZnBtSGxxc3FHaXhIOXl3CmlMck9YTEorMzBDNmxFK2NxWnls
            cUY3MmR6TXMyYWNUWDdpb2tqeVBGeXcKLS0tIGF0cWRFTTlqV1hVRHgrdFJNeGNj
            c0ViS1VwcWUzdVFVZW90Z3Uzc1NPSWcKMhQDlAna6QMcZ6dOmiTICKLOjWmvQqmt
            i8G5CXQajv5/MeLys48C0edQyqzCf9VTClG/hk5YHc2Gh8zGioDarw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lm0sz9afv6fdmpqcfsrhcfvkfcw6rgga20mpplrryxwcppfd6glq959w5j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T01:00:59Z"
    mac: ENC[AES256_GCM,data:k1RzBBkTpXl6X3FUb1C2j/3yZrFhf4DrUvzQt2xDoHdnPTO30tYnCcPeNbwqj5qGlcIjQl0JsXu00R+Vy5GBudqV+lLSSMPYNW00TIlMt9Py7dPlP5QQFNqxUUYPPuYB0S9Xk2Xe8qjnavUiEEVWqAKgJGdHi+rIkcPnAUAK/CQ=,iv:e01eBDVspxXABUPrSel8lN9jHSgi3RfcliVfQOMPn/I=,tag:uGXHib8oNwhJ+2E1HSWBGg==,type:str]
    version: 3.13.3
