apiVersion: v1
kind: Secret
metadata:
    name: executionlab-staging
    namespace: executionlab-staging
type: Opaque
stringData:
    DB_USER: ENC[AES256_GCM,data:9l9+BmMoIYVpyHdP9nlI08wvm7Y=,iv:kLMC7XQ5nPes0baMdU6eezDPd5rZ0vuVv7EhU0/StQQ=,tag:JGdOutEUmHjQkfCXyTJ5Xg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:zLYWzPSXHudd6jXwyzRWpnwGp0a30VNlGZRqxQLFhxg=,iv:JbcrMAoukJPToIQGgGOPnU1sJ37XB16M95nhgamLGy4=,tag:GGlhKbNt/37ORkxZ7MXgcQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:Etwkw2K8j9yNfd9IPvGG6xWypM8=,iv:9HKjaAOJOUkYf1kARjHb2KmqLDtkrzyembDTfSBNyoU=,tag:te3AjFKP5l8Xao3lV4zAKw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:/JGW4qye4kFvWExrOmmRJpuA48gcKvoYRsJnFsHsKq4=,iv:nfUaYot7YThinn29g/+fZSyoV5NWblTGH/gg3bSYKRM=,tag:H6FbSfugpXFQq+yc0CTAnA==,type:str]
    BOT_DB_USER: ENC[AES256_GCM,data:YAB4ZRznX3ydkssVxUEgRSNxTWk=,iv:3u80NDxOvzFdSHo7p4gMMz4mtBSlkk8g0OrUwVauBEY=,tag:vX0zCNOydn4i3/TlNF9rFg==,type:str]
    BOT_DB_PASSWORD: ENC[AES256_GCM,data:kU0b9yCHWmkoflt6LGj0QTOk1nRTH+GNgNx4P9uESsU=,iv:nqDtOwXfD5/ZazZ/QHe+JuL15Noi/32D6qd69cs6N44=,tag:OYtNXQ0yEkDDkcVqzEkXLA==,type:str]
    TASK_DB_USER: ENC[AES256_GCM,data:s1ViLWL0jqOi3OKvnVl1gpLfhr0=,iv:aArJdarV3z1cehJDTHL+54ZGOxUEhmq5QeiWP5csIqE=,tag:R158rjgkn3LOHtcLuV+HzQ==,type:str]
    TASK_DB_PASSWORD: ENC[AES256_GCM,data:bOpvk0ZpHmTVhZ8qGISoGnb4C8imjIM+6tldgyDxoGs=,iv:enxRqlWCQjkPItfrbnc3fIGowc0YTVX/w4Q0N/R3EkM=,tag:2bj1IGh9YcQF1MXgd65ACg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:Dh06UOY0uWRrPCVhK/HeFd3sc6lqKzfH87JU/XMevgari8pYiERbcR0LuRObD+byb5TgLU+p+8hE7spa+UAITNbF6kauHixi8TaElzQdlT3oKwK+H6e3MKl2LO1QltG1MKjAr3PzzIFXgHpDVh2GJ7bxrtblG64HVuOiMqgy1DflO4aE1Ws0Uv4TkUySMx8NrLVl6gw/8up9qbc=,iv:aVRSh+YuFIB1wBXpcmFA9vf1Qy/e9Yki1+0kpgTpEwY=,tag:0KlbOgbl1T33zkCqCN4O1g==,type:str]
    BOT_DATABASE_URL: ENC[AES256_GCM,data:uU2TUr6Xc7RE6CVns657WYiFc3wKI9EhzBfnLLBxFvPvufYW8yRQmnXN9VsO3widBQSBA9XbWDbr+bbVg3Y0F51GdddCsHYvq97nmXAzYBcQFWAuHiNgK5Z1Rm8qh5pkuGM7runWHCOMl/qZaKJJlsCd9hjhE9/D+GK4HcYYVmueFw+1ZiaP7+P8P5BTAWfKbUhpZGcHk6islBtNT6igq9EC0bGUEQ==,iv:o8OviGtjpWiaSOAP1PUJUuHWUl71KOcJcwAuHf4VF64=,tag:UyyJKMDnzmt/U57+HeLYIw==,type:str]
    JWT_SECRET_KEY: ENC[AES256_GCM,data:sB7xdh8fo1iv7AcGuHFRW0wg3G7qVPw1amxcvsrdZHo/BbFiTS/knoIFxZwHNQab,iv:1R4/9oWaBhISPN1U36yg+Aivg8ozCF9lq/ahWhLUJC0=,tag:20l94MCILTSeDS7oEfFlcw==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:t16C+yqroZ5dz3OFA58Ffu/zSenSkqAlDf3W20+ag4cRA2sdQMWLMJ1T1KSdVRX/,iv:4fUlCbFNOo7x5UjntCvfp7lDM25kNtU0NKSkbzNrwIY=,tag:wx/yTpgYunl2FElVxiqpsA==,type:str]
    BOOTSTRAP_ADMIN_USERNAME: ENC[AES256_GCM,data:LrDl0Pg=,iv:L9NgWU/NiJG3158/PwTWbFkDaq5Erd1V+PXlU3zK82E=,tag:Ub+Aye71pGF/yCul79Z7dg==,type:str]
    BOOTSTRAP_ADMIN_EMAIL: ENC[AES256_GCM,data:+wTGyPGWPWu5aDThme0g1Jqrz27E,iv:OahMy+8Ot1xUv8GsoH/WRRjhUxvjw/sb7LgN+7GZwVg=,tag:XKAg+W8EphNgOogFDBnk+A==,type:str]
    BOOTSTRAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:ubmPMtRo3t1dUbNM+nMehU944Ik=,iv:us2vQMWTtLSNwwLec5EFirgjkz0y6viAv/K/fGBM6Po=,tag:/ryW45Mqn/xgh4DvWRz13w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZ0lTZHhmUlFmZEwxdkdM
            QnVxQjlhekdVMnIxc3lHTzJPdURGbU81WEdVClg2b1FtRXg1c1pnS1RxbzVYYWlR
            N3ppYmt5VDM5ZC9FMHZ1OHJhU3VSQkEKLS0tIDNnd2pWanhEWlF4Ny96dXZtdjdW
            N25ITGRDdjNJK1ZOOEtHSXZuNm9mb3MKtZdk5bgWtvANt+GJgF7/I+f01lIYQOnc
            NIb6UyhF/vjNyIjHXoAiUIRITdKNqko39wDyaAiMyHXe2QQLvnUFUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lm0sz9afv6fdmpqcfsrhcfvkfcw6rgga20mpplrryxwcppfd6glq959w5j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T01:18:38Z"
    mac: ENC[AES256_GCM,data:lzHs47tKes7AtBnQNYkEmZRHX26UBfQSqlyNhPn3DiNGJXFS7SSBt7xqp8Wv/6FxTLoUZW+yeT5BY7x9bFq2KSc3xsvTKNgmMKdiqPtS63TNsR6D2tn15TEWpjvRiTsixt1jzKLaQdc1aIsbrwZj7iVCkqA7ck5kKGfhcKSj+dY=,iv:hMJp8kRZjDQ2iDDXHygEmOU0kaAvR/FI40sca8e7+yc=,tag:ejtalNx4U9f6QyRx1ZoTDA==,type:str]
    version: 3.13.3
